### ISSUE TITLE
OAuth4Code.java got javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by guoyibj** [sunxiaowei2014/weibo4j-oauth2-beta3.1.1#16]
DEBUG [2021-07-16 12:47:40]  POSThttps://api.weibo.com/oauth2/access_token
weibo4j.model.WeiboException: Received fatal alert: handshake_failure
	at weibo4j.http.HttpClient.httpRequest(HttpClient.java:412)
	at weibo4j.http.HttpClient.post(HttpClient.java:293)
	at weibo4j.Oauth.getAccessTokenByCode(Oauth.java:79)
	at weibo4j.examples.oauth2.OAuth4Code.main(OAuth4Code.java:21)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at com.ibm.jsse2.j.a(j.java:39)
	at com.ibm.jsse2.j.a(j.java:17)
	at com.ibm.jsse2.qc.b(qc.java:463)
	at com.ibm.jsse2.qc.a(qc.java:482)
	at com.ibm.jsse2.qc.h(qc.java:272)
	at com.ibm.jsse2.qc.a(qc.java:52)
	at com.ibm.jsse2.h.write(h.java:10)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:93)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:151)
	at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:506)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at weibo4j.http.HttpClient.httpRequest(HttpClient.java:387)
	... 3 more

**Comment by guoyibj** [comment]
httpclient.jar 版本太低了，更新httpclient.jar 后可以用了
